### ISSUE TITLE
infura?

### ISSUE THREAD

**Issue by roiLeo** [kodadot/loligo#48]
Do we still have access to `infura_kodadot1`?

**Comment by vikiival** [comment]
most probably yes cc @preschian

**Comment by preschian** [comment]
> most probably yes cc @preschian

yes I still can access the URL https://kodadot1.infura-ipfs.io/ipfs/bafkreibqcoifn4wm2pb34fciwp6hctyc4j2dsfrkr5hokd2v74hmap2gmq

seems like both https://kodadot-ultra.myfilebase.com and https://kodadot1.infura-ipfs.io are owned by @yangwao / @vikiival if you need admin dashboard

we are should be not using https://r2.infura-ipfs.io anymore
