### ISSUE TITLE
Add missing fields to TokenEntities

### ISSUE THREAD

**Issue by vikiival** [kodadot/loligo#51]
> blockNumber

add the block when the tokenEntity has been created

> updatedAt

update the date when the tokenEntity's count (#50) or price (#52) has been changed

> createdAt

add the date when the tokenEntity has been created

**Comment by daiagi** [comment]
>add the block when the tokenEntity has been created

already present

> add the date when the tokenEntity has been created
already present

>update the date when the tokenEntity's count (https://github.com/kodadot/stick/issues/243) or price (https://github.com/kodadot/loligo/issues/52) has been changed

working on it (adding cheapest nft)

**Comment by vikiival** [comment]
@daiagi can we close?
