### ISSUE TITLE
Add Collection Entity to TokenEntity

### ISSUE THREAD

**Issue by vikiival** [kodadot/loligo#53]
>So that means TokenEntity is expecting same image under one collection right?

correct, all of the nfts under one collection that share same ipfs URL are a single TokenEntity

_Originally posted by @daiagi in https://github.com/kodadot/nft-gallery/issues/7462#issuecomment-1744596021_

Task:

1. To `TokenEntity` add `CollectionEntity`

```graphql
type TokenEntity @entity {
  collection: CollectionEntity
}
```

**Comment by vikiival** [comment]
Looks like it's already present

https://github.com/kodadot/stick/blob/f870effae7141dde9668e94dfe771f6fdd7ff596/schema.graphql#L32

**Comment by daiagi** [comment]
Yes it is

**Comment by vikiival** [comment]
> Yes it is

so why we cannot use it in the query?

**Comment by daiagi** [comment]
We can and I will
